version: '3.8'

services:
  backend:
    build:
      context: . 
      dockerfile: app/server/Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - '5000:5000'
    ipc: "host"
    pid: "host"
    stdin_open: true
    tty: true
    environment:
      FLASK_ENV: debug

  client:
    build:
      context: .  
      dockerfile: app/client/Dockerfile
    ports:
      - '3000:3000' 
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true