version: '3.8'

services:
  backend:
    build:
      context: . 
      dockerfile: app/server/Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - '5000:5000'
    ipc: "host"
    pid: "host"
    stdin_open: true
    tty: true
    environment:
      FLASK_ENV: debug

  client:
    build:
      context: ./app/client  
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./app/client:/app  
    environment:
      - CHOKIDAR_USEPOLLING=true