version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/app
    environment:
      FLASK_ENV: development
  
