include:
  - ./app/grafan_plugin_client/docker-compose.prod.yml
  - ./app/server_ai_agent/docker-compose.prod.yml

services:
  backend:
    build:
      context: . 
      dockerfile: app/server/Dockerfile
    ports:
      - '5000:5000'
    ipc: "host"
    pid: "host"
    stdin_open: true
    tty: true
    environment:
      FLASK_ENV: debug