version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - '5000:5000'
    ipc: "host"
    pid: "host"
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
    environment:
      FLASK_ENV: debug
  
