services:
  grafana:
    container_name: 'wisevision-wiseos-app'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-12.2.0-ubuntu}
    network_mode: host
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=wisevision-wiseos-app

      - GF_LOG_LEVEL=debug
      - GF_LOG_MODE=console
    volumes:
      - ./dist:/var/lib/grafana/plugins/wisevision-wiseos-app
      - ./provisioning:/etc/grafana/provisioning
