services:
  grafana:
    container_name: wisevision-wiseos-app
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=wisevision-wiseos-app,wisevision-wiseosvisualization-panel
    volumes:
      - grafana-storage:/var/lib/grafana
      - grafana-panel-b:/var/lib/grafana/plugins/wisevision-wiseosvisualization-panel
    depends_on:
      panel-source:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  grafana-storage:
  grafana-panel-b:
