name: Check npm start for errors

on:
  pull_request:
    branches:
      - dev
      - main
      - 'stabilization/**'
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:   
    runs-on: self-hosted

    container:
      image: node:16

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: wisevision_dashboard_ws

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd wisevision_dashboard_ws/app/client
          npm install

      - name: Run npm start and check for errors
        run: |
          cd wisevision_dashboard_ws/app/client
          npm start &
          sleep 10    
          kill $!

      - name: Clean up workspace
        if: always()
        run: |
          rm -rf wisevision_dashboard_ws 
          
        continue-on-error: false